<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">
        <?php Funcionesphp::noCache() ?>
        <?php echo ICON ?>
        <title><?php echo $this->titulo; ?></title>
        <?php echo FW_JQUERY ?>
        <?php echo FW_BOOTSTRAP ?>
        <?php echo LIB_DATATABLE ?>
        <?PHP ECHO LIB_VALIDATOR ?>
        <?php echo JS_PAGE ?>
        <?php echo CSS_GENERAL ?>
        <link href="<?php echo $_layoutParams['ruta_css']; ?>estilos.css" rel="stylesheet">
        <script src="<?php echo $_layoutParams['ruta_js']; ?>parametros.js"></script>

    </head>

    <body onload="Javascript:history.go(1);" onunload="Javascript:history.go(1);">
        <div title="Click para Cerrar" id="carga">Cargando...</div>