<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="ADSI" content="">
        <title></title>
        <?php echo FW_JQUERY ?>
        <?php echo FW_BOOTSTRAP ?>
        <?php echo JS_PAGE ?>
        <?php echo CSS_GENERAL ?>
    </head>
    <body>