<div class="container"><div class="row">
        <div class="col-md-1"></div>
        <div class="col-md-10">
            <div class="panel panel-warning sombra">
                <div class="panel-heading"><h4 class="label-orange text-center">Trimestres Academicos Diego</h4></div>
                <div class="panel-body">
                    
                    <br />
                    <div class="row">
                        <div class="col-md-12  ">
                            <div class="table-responsive">
                                <table id="datatable" class="table table-condensed table-striped table-bordered table-hover">
                                    <thead>
                                        <tr class="warning">
                                            <th>Id</th>
                                            <th>Trimestre</th>
                                            <th>Año</th>
                                            <th>Fecha Inicio</th>
                                            <th>Fecha Final</th>
                                            
                                        </tr>        
                                    </thead>
                                    <tbody>
                                       
                                            <tr>                         

                                                <td class="text-center">1</td>
                                                <td>Adrian</td>
                                                <td class="text-center">cinco trimestres</td>
                                                <td class="text-center">22/9760/8494</td>
                                                <td class="text-center">23/7666/456456</td>
                                                             
                                            </tr>
                                            <tr>                         

                                                <td class="text-center">2</td>
                                                <td>Juan</td>
                                                <td class="text-center">cinco trimestres</td>
                                                <td class="text-center">22/9760/8494</td>
                                                <td class="text-center">23/7666/456456</td>
                                                             
                                            </tr>
                                            <tr>                         

                                                <td class="text-center">3</td>
                                                <td>Mario</td>
                                                <td class="text-center">cinco trimestres</td>
                                                <td class="text-center">22/9760/8494</td>
                                                <td class="text-center">23/7666/456456</td>
                                                             
                                            </tr>
                                        
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-1"></div>
    </div>
</div>