<div class="container"><div class="row">
        <div class="col-md-1"></div>
        <div class="col-md-10">
            <div class="panel panel-warning sombra">
                <div class="panel-heading"><h4 class="label-orange text-center">Carros Y Motos</h4></div>
                <div class="panel-body ">
                    
                    <br />
                    <div class="row">
                        <div class="col-md-12  ">
                            <div class="table-responsive">
                                <table id="datatable" class="table table-condensed table-striped table-bordered table-hover">
                                    <thead>
                                        <tr class="warning">
                                            <th>Carros</th>
                                            <th>Precios</th>
                                            <th>Motos</th>
                                            <th>Precios</th>
                                            
                                            
                                        </tr>        
                                    </thead>
                                    <tbody>
                                       
                                            <tr>                         

                                                <td class="text-center">toyota</td>
                                                <td>123.000.000</td>
                                                <td class="text-center">susuki</td>
                                                <td class="text-center">4.000.000</td>
                                               
                                                             
                                            </tr>
                                           <tr>                         

                                                <td class="text-center">Campero</td>
                                                <td>150.000.000</td>
                                                <td class="text-center">Honda</td>
                                                <td class="text-center">9.000.000</td>
                                               
                                                             
                                            </tr>
                                            <tr>                         

                                                <td class="text-center">Kia</td>
                                                <td>130.000.000</td>
                                                <td class="text-center">Yamaha</td>
                                                <td class="text-center">6.000.000</td>
                                               
                                                             
                                            </tr>
                                            <tr>                         

                                                <td class="text-center">Renault</td>
                                                <td>176.000.000</td>
                                                <td class="text-center">AKT</td>
                                                <td class="text-center">5.000.000</td>
                                               
                                                             
                                            </tr>
                                        
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-1"></div>
    </div>
</div>