<script>  
 
  </script>

<div class="container">
    <div class="row">
    <div class=" col-md-3"></div>
    <div class=" col-md-6">
        <div class="panel panel-body sombra">
            <div class="text-center">
            <h2 class="text-center">Reportes</h2>
            <h3>¿Nesecitas imprimir un Formato?</h3>
		<p>si nesecita sacar los productos imprima el formlario 1</p>
                <p>si nesecita sacar los productos aca imprima el formlario 2</p>
                <p><a title="imprime el formato numero 1" class="btnPrint btn btn-primary glyphicon glyphicon-print" href='<?php echo BASE_URL . 'sica/reportes/imprimir'; ?>'>1</a></p>
    <p><a title="imprime el formato numero 2" class="btnPrint btn btn-primary glyphicon glyphicon-print" href='<?php echo BASE_URL . 'sica/reportes/imprimir2'; ?>'>2</a></p>
            </div>
    </div>
    </div>
    <div class=" col-md-3"></div>
    </div>
</div>
