<style type="text/css">
    .vert .simply-scroll-clip {
        height: 200px;
    }
</style>
<div class="container">
    <div class="row">
        <div class="col-md-3">
            <div class="panel panel-success sombra">
                <div class="panel-heading">Ofertas Punto de Venta</div>
                <div class="panel-body">
                        
                    <script type="text/javascript">
                        (function ($) {
                            $(function () {
                                $("#scroller1").simplyScroll({
                                    orientation: 'vertical',
                                    customClass: 'vert',
                                    speed: 1,
                                });
                            });
                        })(jQuery);
                    </script>
                    <div class="row">
                        <ul id="scroller1">
                            <?php for ($i = 1; $i <= 10; $i++) { ?>
                                <li>
                                    <div class="col-md-12">
                                        <div><h5 class="label-orange text-uppercase text-left">Producto <?php echo $i ?></h5></div>
                                        <div class="text-right"><h5><strong>$<?php echo $i ?>.000</strong></h5></div>
                                    </div>
                                </li>
                            <?php } ?> 
                        </ul>  
                    </div>
                    <br />
                    <div><a class="btn btn-sm btn-success">Ver todas las ofertas...</a></div>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="panel panel-success sombra">
                <div class="panel-body">
                    <div class="bs-example" data-example-id="carousel-with-captions">
                        <div id="carousel-example-captions" class="carousel slide" data-ride="carousel">
                            <ol class="carousel-indicators">
                                <li data-target="#carousel-example-captions" data-slide-to="0" class="active"></li>
                                <li data-target="#carousel-example-captions" data-slide-to="1"></li>
                                <li data-target="#carousel-example-captions" data-slide-to="2"></li>
                                <li data-target="#carousel-example-captions" data-slide-to="3"></li>
                                <li data-target="#carousel-example-captions" data-slide-to="4"></li>
                            </ol>
                            <div class="carousel-inner" role="listbox">
                                <div class="item active">
                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>up1.jpg" alt="Unidad 1">
                                    <div class="carousel-caption">
                                        <h3>Unidad 1</h3>
                                        <p>Nota 1</p>
                                    </div>
                                </div>
                                <div class="item">
                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>up2.jpg" alt="Unidad 2">
                                    <div class="carousel-caption">
                                        <h3>Unidad 2</h3>
                                        <p>Nota 2</p>
                                    </div>
                                </div>
                                <div class="item">
                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>up3.jpg" alt="Unidad 3">
                                    <div class="carousel-caption">
                                        <h3>Unidad 3</h3>
                                        <p>Nota 3</p>
                                    </div>
                                </div>
                                <div class="item">
                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>up4.jpg" alt="Unidad 4">
                                    <div class="carousel-caption">
                                        <h3>Unidad 4</h3>
                                        <p>Nota 4</p>
                                    </div>
                                </div>
                                <div class="item">
                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>up5.jpg" alt="Unidad 5">
                                    <div class="carousel-caption">
                                        <h3>Unidad 5</h3>
                                        <p>Nota 5</p>
                                    </div>
                                </div>
                            </div>
                            <a class="left carousel-control" href="#carousel-example-captions" role="button" data-slide="prev">
                                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                                <span class="sr-only">Previous</span>
                            </a>
                            <a class="right carousel-control" href="#carousel-example-captions" role="button" data-slide="next">
                                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                                <span class="sr-only">Next</span>
                            </a>
                        </div>
                    </div><!-- /example -->
                </div>
            </div>

        </div>

        <div class="col-md-3 ">
            <div class="panel panel-success sombra">
                <div class="panel-heading">Información de Usuario</div>
                <div class="panel-body">
                    Nombre, Documento, ROl, Responsabilidasdes
                </div>
            </div>
            <div class="panel panel-success sombra">
                <div class="panel-heading">Información de interes</div>
                <div class="panel-body">
                    Info 1  -- $660.000
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8">
            <div class="panel panel-default sombra">
                <div class="panel-body">
                    <h4 class="label-orange">SICEFA y el Centro de Formación Agroindustrial</h4>
                    <p>SICEFA ofrece al centro de formación agroindustrial “La Angostura”, un conjunto de aplicaciones web 2.0, que permiten gestionar eficientemente la información académica, técnica y administrativa de las áreas productivas de la finca, así como también permite gestionar otras áreas que aportan significativamente al control y buen manejo de los bienes y talento humano del CEFA.</p>
                    <p>SICEFA Nació como proyecto formativo del programa Tecnológico en Análisis y Desarrollo de sistemas de Información (ADSI), el cual ha evolucionado en su concepción, funcionalidad y metodología de desarrollo desde el primer curso que inicio el proyecto en 2009; Hoy podemos decir que tenemos una herramienta madura en cuanto al conocimiento de las áreas implicadas y que cuenta con estandares de calidad en el desarrollo usando herramientas actuales de gran acogida.</p></div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="panel panel-success sombra">
                <div class="panel-heading">Nuestro Centro en Google Maps</div>
                <div class="panel-body">
                    <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d2503.4617022564894!2d-75.36157748447157!3d2.6120133279821505!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e1!3m2!1ses!2s!4v1423750155182" width="100%" height="100%" frameborder="0" style="border:0"></iframe>
                    <br />
                    <div><a class="btn btn-sm btn-success">Conoce nuestro centro...</a></div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8">
            <div class="panel panel-success sombra">
                <div class="panel-body">
                    <h4 class="label-orange">SICEFA y la Estrategia Sena-Empresa</h4>
                    <p>SICEFA ofrece a la estrategia de Sena empresa una mejor administración en cuanto al  modelo de simulación empresarial que se está ejecutando en el  CEFA, esto se hace con el fin  que los aprendices   puedan vivenciar de manera real todas las situaciones que se pueden presentar en los procesos: administrativos, 
                        productivos, financieros y de comercialización de una empresa;  para fortalecer lo antes mencionado SICEFA da al aprendiz una buena administración en la cual los aprendices encargados de SENA EMPRESA puedan llevar un mejor orden en cuanto sus reportes, turnos encargados, bodegas, inventarios, administración de personal, movimientos entre unidades, punto de venta y área de contabilidad, dependiendo de su unidad o área encargada
                    </p></div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="panel panel-success sombra">
                <div class="panel-heading">Video Introductorio</div>
                <div class="panel-body">
                    <iframe width="100%" height="100%" src="https://www.youtube.com/embed/M37yMgyKkgA?rel=0&showinfo=0&modestbranding=1" frameborder="0" allowfullscreen></iframe>
                </div>
            </div>
        </div>
    </div>
    <div class="alert alert-success sombra text-center" role="alert">
        <strong> APLICACIONES</strong>
    </div>

    <div class="row">
        <?php for ($i = 0; $i < count($this->aplicativos); $i++) {
            ?>
            <div class="col-md-4">
                <div class="panel panel-success sombra">
                    <div class="panel-heading initialism"><?php echo $this->aplicativos[$i]['avosNombre'] ?></div>
                    <div class="panel-body">
                        <div class="col-md-12">
                            <a class="thumbnail">
                                <img src="<?php echo $_layoutParams['ruta_img']; ?><?php echo $this->aplicativos[$i]['avosRuta'] ?>.png" alt="...">
                            </a>
                        </div>
                        <div class="text-center"><?php echo $this->aplicativos[$i]['avosDescripcion'] ?></div>
                    </div>
                </div>
            </div>
        <?php } ?>
    </div>
</div>