<div class="container">
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <div class="panel panel-warning sombra">
                <div class="panel-heading"><h4 class="label-orange"><?php echo $this->titulopanel ?></h4></div>
                <div class="panel-body">
                    <form id="form1" name="form1" class="form-horizontal" method="post" action="<?php echo BASE_URL . 'sica/parametros/savetrimestre'; ?>">
                        <input type="hidden"name="txtId" id="txtId" value="<?php echo $this->unturno[0]['trnoId'] ?>" />
                        <fieldset>
                            <div class="form-group">
                                <label class="col-lg-4 control-label">Nombre <sup class="text-danger">*</sup></label>
                                <div class="col-lg-6">
                                    <input type="text" class="form-control" name="txtNombreTipo" id="txtNombreTipo" value="<?php echo $this->unturno[0]['trnoNombre'] ?>" required />
                                </div>
                            </div>
                            </fieldset>
                        <div class="form-group">
                            <div class="text-center">
                                <button type="submit" class="btn btn-primary" id="btnGuardar">Guardar</button>
                                <a class="btn btn-danger" href="<?php echo BASE_URL . 'sica/parametros/'; ?>" >Cancelar</a>
                                <button type="button" class="btn btn-info" id="resetBtn">Limpiar</button>
                            </div>
                        </div>
                    </form>     
                </div>   
            </div>

        </div>
        <div class="col-md-2"></div>
    </div>
</div>
