<div class="container">
    <div class="row">
        <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="bs-example" data-example-id="carousel-with-captions">
                        <div id="carousel-example-captions" class="carousel slide" data-ride="carousel">
                            <ol class="carousel-indicators">
                                <li data-target="#carousel-example-captions" data-slide-to="0" class="active"></li>
                                <li data-target="#carousel-example-captions" data-slide-to="1"></li>
                                <li data-target="#carousel-example-captions" data-slide-to="2"></li>
                                <li data-target="#carousel-example-captions" data-slide-to="3"></li>
                                <li data-target="#carousel-example-captions" data-slide-to="4"></li>
                                 <li data-target="#carousel-example-captions" data-slide-to="5"></li>
                            </ol>
                            <div class="carousel-inner" role="listbox">
                                <div class="item active">
                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>s1.png" alt="Unidad 1">
                                    <div class="carousel-caption">

                                    </div>
                                </div>
                                <div class="item">
                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>s2.png" alt="Unidad 2">
                                    <div class="carousel-caption">

                                    </div>
                                </div>
                                <div class="item">
                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>s3.png" alt="Unidad 3">
                                    <div class="carousel-caption">

                                    </div>
                                </div>
                                <div class="item">
                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>s4.png" alt="Unidad 4">
                                    <div class="carousel-caption">


                                    </div>
                                </div>
                                <div class="item">
                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>s5.png" alt="Unidad 5">
                                    <div class="carousel-caption">

                                    </div>
                                </div>
                                <div class="item">
                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>s6.png" alt="Unidad 5">
                                    <div class="carousel-caption">

                                    </div>
                                </div>                     
                            </div>
                            <a class="left carousel-control" href="#carousel-example-captions" role="button" data-slide="prev">
                                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                                <span class="sr-only">Previous</span>
                            </a>
                            <a class="right carousel-control" href="#carousel-example-captions" role="button" data-slide="next">
                                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                                <span class="sr-only">Next</span>
                            </a>
                        </div>
                    </div><!-- /example -->
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-heading">    BANDEJA DE ENTRADA</div>
                <div class="panel-body">
                    <p>
                        Alistamiento de terreno 
                    </p>
                    <p>
                        Siembra de arroz
                    </p>
                    <p>

                    </p>

                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-body">
                    <p>
                        Una de las principales líneas tecnológicas del centro de Formación Agroindustrial “La Angostura” regional Huila; 
                        ubicado en el municipio de Campoalegre es la de Tecnología Agrícola, por lo cual es importante disponer de una herramienta informática que permita manejar la información de dicha área de manera ágil y oportuna.
                    </p>
                    <p>
                        En el Centro De Formación Agroindustrial “La Angostura” 
                        se implementan cultivos permanentes, semipermanentes y transitorios, los cuales tienen cuidados y manejos especiales.
                    </p>
                    <p>
                        El Sistema De Información Agrícola (SIA) brinda una herramienta para registrar y administrar eficientemente la información de esta área productiva, facilitando la implementación de las buenas prácticas 
                        agrícolas en todas las labores del cultivo, tales como: alistamiento de terreno, siembra, riego, disposición de utensilio, fertilización, insumos agrícolas, poda, cosecha, entre otras. 
                    </p>

                </div>
            </div>
        </div>
    </div>
    <div class="col-md-3"></div>
</div>
</div>


</div>

