<div class="container">
    <div class="row">
        <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="bs-example" data-example-id="carousel-with-captions">
                        <div id="carousel-example-captions" class="carousel slide" data-ride="carousel">
                            <ol class="carousel-indicators">
                                <li data-target="#carousel-example-captions" data-slide-to="0" class="active"></li>
                                <li data-target="#carousel-example-captions" data-slide-to="1"></li>
                                <li data-target="#carousel-example-captions" data-slide-to="2"></li>
                                <li data-target="#carousel-example-captions" data-slide-to="3"></li>
                                <li data-target="#carousel-example-captions" data-slide-to="4"></li>
                                <li data-target="#carousel-example-captions" data-slide-to="5"></li>
                                <li data-target="#carousel-example-captions" data-slide-to="6"></li>
                                <li data-target="#carousel-example-captions" data-slide-to="7"></li>
                            </ol>
                            <div class="carousel-inner" role="listbox">
                                <div class="item active">
                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>1.png" alt="Unidad 1">
                                    <div class="carousel-caption">
                                        <h3>Unidad 1</h3>
                                        <p>Nota 1</p>
                                    </div>
                                </div>
                                <div class="item">
                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>2.png" alt="Unidad 2">
                                    <div class="carousel-caption">
                                        <h3>Unidad 2</h3>
                                        <p>Nota 2</p>
                                    </div>
                                </div>
                                <div class="item">
                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>3.png" alt="Unidad 3">
                                    <div class="carousel-caption">
                                        <h3>Unidad 3</h3>
                                        <p>Nota 3</p>
                                    </div>
                                </div>
                                <div class="item">
                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>4.png" alt="Unidad 4">
                                    <div class="carousel-caption">
                                        <h3>Unidad 4</h3>
                                        <p>Nota 4</p>
                                    </div>
                                </div>
                                <div class="item">
                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>5.png" alt="Unidad 5">
                                    <div class="carousel-caption">
                                        <h3>Unidad 5</h3>
                                        <p>Nota 5</p>
                                    </div>
                                </div>
                                <div class="item">
                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>6.png" alt="Unidad 6">
                                    <div class="carousel-caption">
                                        <h3>Unidad 6</h3>
                                        <p>Nota 6</p>
                                    </div>
                                </div>
                                <div class="item">
                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>7.png" alt="Unidad 7">
                                    <div class="carousel-caption">
                                        <h3>Unidad 7</h3>
                                        <p>Nota 7</p>
                                    </div>
                                </div>
                                <div class="item">
                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>8.png" alt="Unidad 8">
                                    <div class="carousel-caption">
                                        <h3>Unidad 8</h3>
                                        <p>Nota 8</p>
                                    </div>
                                </div>
                            </div>
                            <a class="left carousel-control" href="#carousel-example-captions" role="button" data-slide="prev">
                                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                                <span class="sr-only">Previous</span>
                            </a>
                            <a class="right carousel-control" href="#carousel-example-captions" role="button" data-slide="next">
                                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                                <span class="sr-only">Next</span>
                            </a>
                        </div>
                    </div><!-- /example -->
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-heading text-center"><strong>Bandeja de Entrada</strong></div>
                <div class="panel-body">
                    <div class="col-md-12 ">
                       
                        <ul>
                            <li>Entrada de Contabilidad por area productivas<span class="glyphicon glyphicon-exclamation-sign text-right btn" style="color:#c9302c"></span></li>
                            <li>Solicitudes de Vacantes cargos Emprecefa<span class="glyphicon glyphicon-exclamation-sign text-right btn" style="color:#c9302c"></span></li>
                            <li>Por Definir...<span class="glyphicon glyphicon-exclamation-sign text-right btn" style="color:#c9302c"></span></li> 
                            <li>Por Definir...<span class="glyphicon glyphicon-exclamation-sign text-right btn" style="color:#c9302c"></span></li>
                        </ul>
                       
                        
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-body">
                    <p class=" text-justify">SICA “SISTEMA INTEGRADO DE CONTROL ADMINISTRATIVO”
                        Es un Aplicativo Web que permitirá al usuario Manejar la  Información
                        de Emprecefa. De tal Manera que Sea de fácil manejo, Seguro, Eficiente
                        y eficaz. Permitirá Manejar La parte Administrativa, Contable De la Empresa
                        de los aprendices e instructores del CEfA, además permitirá Gestionar los turnos
                        de Emprecefa donde se podrá llevar el control de asistencia por medio de un módulo 
                        en Android y También estará disponible  dentro del aplicativo web.
                        Manejara Talento Humano, Donde se manejara la parte de nómina y donde Podrán
                        ser Registrados más cargos para la empresa (Emprecefa).
</p>
                </div>
            </div>
        </div>
    </div>



</div>

