<div class="container">
   <div class="row">
        <div class="col-md-12">
            <div class="panel panel-success">
                 <div class="panel-heading"><h3 class="text-center"><strong>Asistencia a Turnos Emprecefa</strong></h3></div>
                <div class="panel-body">
                    <form id="form1" name="form1" class="" data-toggle="modal" role="form" action="" method="post">
                        <div class="col-md-12">

                            <div class="col-md-4">
                                <label> Seleccione Titulacion</label>
                                <select id="cmbTitulacion" name="cmbTitulacion" >
                                    <option disabled="disabled" value="" selected="">---Seleccione---</option>
                                    <?php for ($j = 0; $j < count($this->titulaciones); $j++): ?>
                                        <option value="<?php echo $this->titulaciones[$j] ['Id']; ?>" ><?php echo $this->titulaciones[$j] ['nomtitulaciones']; ?>,<?php echo $this->titulaciones[$j] ['fichatitulaciones']; ?></option>
                                    <?php endfor; ?>
                                </select>
                            </div>
                            
                            <div class="col-md-4">
                                <label>Fecha</label>
                                <select id="cmbfecha" name="cmbfecha" >
                                    <option disabled="disabled" value="" selected="">--aaa/mmm/ddd---</option>
                                    <?php for ($i = 0; $i < count($this->datos); $i++): ?>
                                        <option value="<?php echo $this->datos[$i] ['Fecha']; ?>"><?php echo $this->datos[$i] ['Fecha']; ?></option>
                                    <?php endfor; ?>
                                </select>
                            </div>
                            <div class="col-md-4">
                                <label>Area</label>
                                <select id="cmbarea" name="cmbarea" onchange=document.form1.submit()>
                                    <option disabled="disabled" value="" selected="">---Seleccione---</option>
                                    <?php for ($j = 0; $j < count($this->areas); $j++): ?>
                                        <option value="<?php echo $this->areas[$j] ['Id']; ?>" ><?php echo $this->areas[$j] ['Nombre']; ?></option>
                                    <?php endfor; ?>
                                </select>
                            </div>

                        </div>
                        <div class="col-md-12 ">
                            <div class="col-md-4 table-bordered">
                                <label>Nombre Del Aprendiz</label>

                            </div>
                            <div class="col-md-4 table-bordered">
                                <label>Asistencia</label>

                            </div>
                            <div class="col-md-4 table-bordered">
                                <label>Observación</label>

                            </div>
                        </div>
                        <?php for ($i = 0; $i < count($this->asistencia); $i++): ?>
                            <div class="col-md-12">

                                <div class=" table-bordered">
                                    <div class="col-md-4 ">
                                        <label><?php echo $this->asistencia[$i] ['nombreaprendiz']; ?></label>

                                    </div>
                                    <div class="col-md-4 ">
                                        <div>
                                            <label class="">
                                                <input  type="radio" name="asistencia" value="si" required="" />
                                                <label>si</label>
                                                &ThinSpace;
                                                <input  type="radio" name="asistencia" value="no" required="" />
                                                <label>No</label>

                                            </label>
                                        </div>
                                    </div>
                                    <div class="col-md-4 ">
                                        <div>
                                            <textarea class="col-md-12" name="" id=""></textarea>
                                        </div>
                                    </div>
                                </div>

                            </div>

                        <?php endfor; ?>
                        <div class="row col-md-12 text-center">
                            <div><br></div>
                            <a class="btn btn-primary" data-toggle="modal" data-target="#miventana1" href="#">guardar</a>
                            <div class="modal fade bs-example-modal-sm " id="miventana1" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
                                <div class="modal-dialog ">
                                    <div class="modal-content">
                                        <div class="modal-body">
                                            <button type="button" class="close" data-dismiss="modal" aria-hidenn="true">&times;</button>
                                            <h3>Esta Seguro Que Desea guardar los turnos</h3>
                                        </div>

                                        <div class="modal-footer discurso-enfatizado">
                                            <a class="btn btn-sm btn-primary " data-dismiss="modal" href="#" role="button">No</a>
                                            <a class="btn btn-sm btn-primary " href="#" role="button">Sí</a>
                                        </div>
                                    </div>
                                </div>          
                            </div>

                            <a class="btn btn-primary" data-toggle="modal" data-target="#miventana2" href="#">Editar</a>
                            <div class="modal fade bs-example-modal-sm " id="miventana2" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
                                <div class="modal-dialog ">
                                    <div class="modal-content">
                                        <div class="modal-body">
                                            <button type="button" class="close" data-dismiss="modal" aria-hidenn="true">&times;</button>
                                            <h3>Esta Seguro Que Desea Editar los turnos</h3>
                                        </div>

                                        <div class="modal-footer discurso-enfatizado">
                                            <a class="btn btn-sm btn-primary " data-dismiss="modal" href="#" role="button">No</a>
                                            <a class="btn btn-sm btn-primary " href="#" role="button">Sí</a>
                                        </div>
                                    </div>
                                </div>          
                            </div>
                            <a class="btn btn-primary" data-toggle="modal" data-target="#miventana3" href="#">Cancelar</a>
                            <div class="modal fade bs-example-modal-sm " id="miventana3" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
                                <div class="modal-dialog ">
                                    <div class="modal-content">
                                        <div class="modal-body">
                                            <button type="button" class="close" data-dismiss="modal" aria-hidenn="true">&times;</button>
                                            <h3>Esta Seguro Que Desea cancelar los turnos</h3>
                                        </div>

                                        <div class="modal-footer discurso-enfatizado">
                                            <a class="btn btn-sm btn-primary " data-dismiss="modal" href="#" role="button">No</a>
                                            <a class="btn btn-sm btn-primary " href="#" role="button">Sí</a>
                                        </div>
                                    </div>
                                </div>          
                            </div>
                            <a class="btn btn-primary" href="">Atras</a>

                        </div>
                    </form>
                </div>

            </div>
        </div>
    </div>
</div>
</div>



</div>
