<div class="container">
    <div class="row">
        <div class="col-md-4">
            <div class="panel panel-success sombra">
                <div class="panel-heading"><h3  class="label-orange text-center">Área Agrícola</h3></div>
                <div class="panel-body">
                    <div class="col-md-12">
                        <a class="thumbnail">
                            <img src="<?php echo $_layoutParams['ruta_img']; ?>up3.jpg" alt="...">
                        </a>
                    </div>
                    <div><p class="text-justify">Está área cuenta con cultivos y unidades tales como:</p>
                        <ul>
                            <li class="text-left">Unidad de Cítricos</li>
                            <li class="text-left">Unidad de Pasifloras</li>  
                            <li class="text-left">Unidad de Policultivo (cacao, papaya y plátano)</li>
                            <li class="text-left">Unidad de Cacao</li> 
                            <li class="text-left">Unidad de Vivero los Cítricos</li>
                            <li class="text-left">Unidad de Guanabana-Anón</li>
                            <li class="text-left">Unidad de Fluor</li>
                            <li class="text-left">Unidad de Café</li>
                            <li class="text-left">Unidad de Mango</li>
                        </ul></div>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="panel panel-success sombra">
                <div class="panel-heading"><h3  class="label-orange text-center">Área Pecuaria</h3></div>
                <div class="panel-body">
                    <div class="col-md-12">
                        <a class="thumbnail">
                            <img src="<?php echo $_layoutParams['ruta_img']; ?>up5.jpg" alt="...">
                        </a>
                    </div>
                    <div><p class="text-justify">Está área cuenta con unidades tales como:</p>
                        <ul>
                            <li class="text-left">Unidad de Bovinos</li>
                            <li class="text-left">Unidad de Ovinos</li> 
                            <li class="text-left">Unidad de Porcinos</li>
                            <li class="text-left">Unidad de Cunícultura</li>  
                            <li class="text-left">Unidad de Apícultura</li>  
                            <li class="text-left">Unidad de Avícola (pollos de engorde, aves de postura)</li>
                            <li class="text-left">Unidad de Piscicultura</li>  
                        </ul>
                        <p>&nbsp;</p>
                        <p>&nbsp;</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="panel panel-success sombra">
                <div class="panel-heading"><h3  class="label-orange text-center">Área Ambiental</h3></div>
                <div class="panel-body">
                    <div class="col-md-12">
                        <a class="thumbnail">
                            <img src="<?php echo $_layoutParams['ruta_img']; ?>up4.jpg" alt="...">
                        </a>
                    </div>
                    <div><p class="text-justify">Está área cuenta con unidades tales como:</p>
                        <ul>
                            <li class="text-left">Abonos Orgánicos</li>
                            <li class="text-left">Vivero Ornamental Forestal y Medicinal</li>  
                            <li class="text-left">Zona Ecológica</li>
                            <li class="text-left">Zona Agroecológica</li> 
                            <li class="text-left">Lombricultivo</li>
                        </ul>
                        <p>&nbsp;</p>
                        <p>&nbsp;</p>
                        <p>&nbsp;</p>
                        <p>&nbsp;</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <div class="panel panel-success sombra">
                <div class="panel-heading"><h3 class="label-orange text-center">Área Agroindustrial</h3></div>
                <div class="panel-body">
                    <div class="col-md-12">
                        <a class="thumbnail">
                            <img src="<?php echo $_layoutParams['ruta_img']; ?>up1.jpg" alt="...">
                        </a>
                    </div>
                    <div> <p class="text-justify">Esta área cuenta con unidades tales como:</p>
                        <ul>
                            <li class="text-left">Planta de lácteos</li>
                            <li class="text-left">Planta de Fluhort</li>  
                            <li class="text-left">Planta de Cárnicos</li>
                            <li class="text-left">Planta de Panificación</li> 
                            <li class="text-left">Procesamiento de Café</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="panel panel-success sombra">
                <div class="panel-heading"><h3  class="label-orange text-center">Área de las TIC'S</h3></div>
                <div class="panel-body">
                    <div class="col-md-12">
                        <a class="thumbnail">
                            <img src="<?php echo $_layoutParams['ruta_img']; ?>up4.jpg" alt="...">
                        </a>
                    </div>
                    <div><p class="text-justify">Está área cuenta con unidades tales como:</p>
                        <ul>
                            <li class="text-left">Desarrollo de Software</li>
                            <li class="text-left">Mantenimiento de Hardware</li> 
                            <li class="text-left">Asesorías Informáticas</li>  
                        </ul>
                    <p>&nbsp;</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="panel panel-success sombra">
                <div class="panel-heading"><h3  class="label-orange text-center">Área Administrativa</h3></div>
                <div class="panel-body">
                    <div class="col-md-12">
                        <a class="thumbnail">
                            <img src="<?php echo $_layoutParams['ruta_img']; ?>up2.jpg" alt="...">
                        </a>
                    </div>
                    <div><p class="text-justify">Esta área cuenta con unidades tales como:</p>
                        <ul>
                            <li class="text-left">Gerencia</li>
                            <li class="text-left">Contable</li>  
                            <li class="text-left">Talento Humano</li>
                        </ul>
                    <p>&nbsp;</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <div class="panel panel-success sombra">
                <div class="panel-heading"><h3  class="label-orange text-center">Área de Comercialización y Mercadeo</h3></div>
                <div class="panel-body">
                    <div class="col-md-12">
                        <a class="thumbnail">
                            <img src="<?php echo $_layoutParams['ruta_img']; ?>up5.jpg" alt="...">
                        </a>
                    </div>
                    <div><p class="text-justify">Está área cuenta con unidades tales como:</p>
                        <ul>
                            <li class="text-left">Estación de Café</li>
                            <li class="text-left">Punto de Venta</li>  
                        </ul></div>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="panel panel-success sombra  ">
                <div class="panel-heading"><h3  class="label-orange text-center">Área de Investigación</h3></div>
                <div class="panel-body">
                    <div class="col-md-12">
                        <a class="thumbnail">
                            <img src="<?php echo $_layoutParams['ruta_img']; ?>up1.jpg" alt="...">
                        </a>
                    </div>
                    <div><p class="text-justify">Está área cuenta con unidades tales como:</p>
                        <ul>
                            <li class="text-left">Semillero de Investigación</li>  
                        </ul>
                    <p>&nbsp;</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="panel panel-success sombra  ">
                <div class="panel-heading"><h3  class="label-orange text-center">Área de Proyectos</h3></div>
                <div class="panel-body">
                    <div class="col-md-12">
                        <a class="thumbnail">
                            <img src="<?php echo $_layoutParams['ruta_img']; ?>up1.jpg" alt="...">
                        </a>
                    </div>
                    <div>
                        <p class="text-justify">Está área cuenta con unidades tales como:</p>
                        <ul>
                            <li class="text-left">Emproyect</li>
                        </ul> 
                        <p>&nbsp;</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



