<div class="container">
    <div class="row">
        <div class="col-md-4">
            <div class="panel panel-success sombra">
                <div class="panel-heading"><h3 class="label-orange text-center">Logo</h3></div>
                <div class="panel-body">
                    <div class="col-md-12">            
                        <img width="100%" height="100%" src="<?php echo $_layoutParams['ruta_img']; ?>LogoEmprecefa.png" alt="...">
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="panel panel-success sombra">
                <div class="panel-heading"><h3 class="label-orange text-center">¿Que es Sena-Empresa?</h3></div>
                <div class="panel-body">

                    <p class="text-center">
                        Sena empresa  es un  modelo didáctico de empresa, que  busca impartir  y trasmitir a el aprendiz los conocimientos administrativos, productivos, técnicos, financieros, ambiéntales, y de comercialización adquiridos  en el proceso  de  formación por medio del manejo real  de una empresa en  las diferentes áreas y  unidades productivas.
                    </p>
                    <p class="text-center">
                        Es  el espacio  ofrecido para formar profesionales integrales con capacidad de análisis y toma dediciones en el entorno empresarial, mediante la innovación e investigación.
                    </p>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="panel panel-success sombra">
                <div class="panel-heading"><h3 class="label-orange text-center">Objetivo</h3></div>
                <div class="panel-body">
                    <p class="text-justify">El aprendiz debe participar activamente en la:</p>
                    <ul>
                        <li class="text-left">Formación</li>
                        <li class="text-left">Producción</li>  
                        <li class="text-left">Comercialización</li>
                    </ul>
                </div>
            </div>
        </div>

    </div>
    <div class="row">
        <div class="col-md-4">
            <div class="panel panel-success sombra">
                <div class="panel-heading"><h3 class="label-orange text-center">Misión</h3></div>
                <div class="panel-body">
                    <a class="thumbnail">
                        <img src="<?php echo $_layoutParams['ruta_img']; ?>mision.jpg" alt="...">
                    </a>
                    <p class="text-center">
                        Fortalecer la formación por competencias desde las estrategias de formación por proyectos, impulsando el emprendimiento, la innovación, la investigación y el trabajo colaborativo, para tener un ambiente de aprendizaje integral en que los aprendices a través del aprender haciendo y el hacer transformado se integren con diferentes especialidades que lo lleven a adquirir todas las competencias adquiridas para la gestión empresarial de proyectos. 
                    </p>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="panel panel-success sombra">
                <div class="panel-heading"><h3 class="label-orange text-center">Visión</h3></div>
                <div class="panel-body">
                    <a class="thumbnail">
                        <img src="<?php echo $_layoutParams['ruta_img']; ?>vision.jpg" alt="...">
                    </a>
                    <p class="text-center">
                        Un modelo empresarial organizado mostrando resultados con proyectos formativos-productivos  que lleven al aprendiz, al empresario y a cualquier ciudadano a implementar en su entorno proyectos empresariales enfocados al desarrollo de la región (nación, departamento, municipio) implementando tecnologías innovadoras que conduzcan a un desarrollo sostenible.
                    </p>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="panel panel-success sombra">
                <div class="panel-heading"><h3 class="label-orange text-center">Modelo Sena-Empresa</h3></div>

                <div class="panel-body">
                    <a class="thumbnail">
                        <img src="<?php echo $_layoutParams['ruta_img']; ?>modelo.jpg" alt="...">
                    </a>
                    <p class="text-center">
                        La Sena Empresa consta de Resultados de Aprendizaje en:
                        Desarrollo de labores administrativas y de mercadeo en la empresa agropecuaria o agroindustrial.
                        Operación del sistema productivo de tipo agropecuario ó agroindustrial.
                        Competencias comportamentales.
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>