<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-success sombra">
                <div class="panel-heading"><h3 class="label-orange text-center">Organigrama</h3></div>
                <div class="panel-body">
                    <div class="col-md-12">            
                        <img width="100%" height="100%" src="<?php echo $_layoutParams['ruta_img']; ?>cronograma.png" alt="...">
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>