<div class="container">
    <div class="row">
        <div class="col-md-3">
            <div class="panel panel-default sombra">
                <div class="panel-heading">Barra de ???</div>
                <div class="panel-body">
                    <button class="btn btn-group-sm btn-info col-md-12">Edificaciones</button>
                    <button class="btn btn-group-sm btn-info col-md-12">Unidad Agricola</button>
                    <button class="btn btn-group-sm btn-info col-md-12">Unidad Pecuaria</button>
                </div>
            </div>
        </div>       
        <div class="col-md-9">
            <div class="panel panel-default sombra">
                <div class="panel-body">

                    <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d2503.4617022564894!2d-75.36157748447157!3d2.6120133279821505!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e1!3m2!1ses!2s!4v1423750155182" width="100%" height="400px" frameborder="0" style="border:0"></iframe>

                </div>
            </div>
        </div>

    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default sombra">
                <div class="panel-body">
                    Este aplicativo es un sistema que permitira visualizar la informacion descriptiva de cada unidad productiva atravez de los mapas google que nos ayuda a localizar las areas por puntos georeferenciado.
                    el administrador permitira ingresar, modificar, y generar reportes de cada sector.
                </div>
            </div>
        </div>
    </div>

</div>
<div class="col-md-3"></div>
</div>
</div>


</div>

