<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="ADSI" content="">
        <?php Funcionesphp::noCache() ?>
        <?php echo ICON ?>
        <title><?php echo $this->titulo; ?></title>
        <?php echo FW_JQUERY ?>
        <?php echo FW_BOOTSTRAP ?>
        <?php echo LIB_SIMPLYSCROLL ?>
        <?php echo LIB_DATATABLE ?>
        <?PHP echo LIB_VALIDATOR ?>
        <?php echo JS_PAGE ?>
        <?php echo CSS_GENERAL ?>
        <link href="<?php echo $_layoutParams['ruta_css']; ?>estilos.css" rel="stylesheet">
        <script src="<?php echo $_layoutParams['ruta_js']; ?>parametros.js"></script>
    </head>
    <body onload="Javascript:history.go(1);" onunload="Javascript:history.go(1);">
        <div class="container">
            <div class="carousel" >
                <div class="carousel-inner " >
                    <div class="item active banner">
                        <img src="<?php echo $_layoutParams['ruta_img']; ?>banner<?php echo $_layoutParams['app']; ?>.png" alt="..." title="esta es la imajen de sicefa">
                    </div> 
                </div>
            </div>
        </div>
        <div class="separate"></div>
        <!-- Fixed navbar -->
        <div class="navbar navbar-custom" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo BASE_URL ?>"><?php echo APP_NAME ?></a>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <?php if (isset($this->menu)): ?>
                            <?php for ($i = 0; $i < count($this->menu); $i++): ?>
                                <?php if ($this->menu[$i]['sub'] != '') { ?>
                                    <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="<?php echo $this->menu[$i]['enlace']; ?>"><?php echo $this->menu[$i]['titulo']; ?><span class="caret"></span></a>                                          
                                        <ul class="dropdown-menu" role="menu">
                                            <?php for ($j = 0; $j < count($this->menu[$i]['sub']); $j++): ?>
                                                <li ><a href="<?php echo $this->menu[$i]['sub'][$j]['enlace']; ?>"><?php echo $this->menu[$i]['sub'][$j]['titulo']; ?></a>

                                                <?php endfor; ?>
                                        </ul>
                                        <?php
                                    }
                                    else {
                                        ?>
                                    <li><a href="<?php echo $this->menu[$i]['enlace']; ?>"><?php echo $this->menu[$i]['titulo']; ?></a>
                                        <?php
                                    }
                                    ?>                           
                                </li>

                            <?php endfor; ?>
                        <?php endif; ?>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <?php if (isset($_layoutParams['menu_user'])): ?>
                            <?php for ($i = 0; $i < count($_layoutParams['menu_user']); $i++): ?>
                                <?php if ($_layoutParams['menu_user'][$i]['sub'] != '') { ?>
                                    <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="<?php echo $_layoutParams['menu_user'][$i]['enlace']; ?>"><?php echo $_layoutParams['menu_user'][$i]['titulo']; ?><span class="caret"></span></a>                                          
                                        <ul class="dropdown-menu" role="menu">
                                            <?php for ($j = 0; $j < count($_layoutParams['menu_user'][$i]['sub']); $j++): ?>
                                                <li ><a href="<?php echo $_layoutParams['menu_user'][$i]['sub'][$j]['enlace']; ?>"><?php echo $_layoutParams['menu_user'][$i]['sub'][$j]['titulo']; ?></a>

                                                <?php endfor; ?>
                                        </ul>
                                        <?php
                                    }
                                    else {
                                        ?>
                                    <li><a href="<?php echo $_layoutParams['menu_user'][$i]['enlace']; ?>"><?php echo $_layoutParams['menu_user'][$i]['titulo']; ?></a>
                                        <?php
                                    }
                                    ?>                           
                                </li>

                            <?php endfor; ?>
                        <?php endif; ?>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </div>
        <div title="Click para Cerrar" id="carga">Cargando...</div>

