
<div class="container">
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <div class="panel panel-success">
                <div class="panel-heading">Habilitar Aprendiz</div>
                <div class="panel-body">
                    <form id="form1" name="form1" class="form-horizontal" action="" method="post">

                        <fieldset>
                            <div class="form-group">
                                <label class="col-md-4 control-label">Documento <sup class="text-danger">*</sup></label>
                                <div class="col-md-6">
                                    <div class="col-md-10"><input type="text" class="form-control" name="txtDocumento" id="txtDocumento" value="" required /></div><div class="col-md-2"><button name="btnBuscar" id="btnBuscar" class="btn btn-default glyphicon glyphicon-search"></button></div>
                                </div>
                                <div id="datos" class="col-md-12"></div>
                            </div>                         
                            <div class="form-group">
                                <div class="text-center">
                                    <button type="submit" class="btn btn-primary" id="btnGuardar">Habilitar</button>
                                    <a class="btn btn-success" href="<?php echo BASE_URL . 'sigac/parametros/trimestre'; ?>" >Registrar</a>
                                    <button type="button" class="btn btn-info" id="resetBtn">Limpiar</button>
                                </div>
                            </div>
                        </fieldset>

                    </form>
                </div>
            </div>
        </div>
        <div class="col-md-2"></div>
    </div>
</div>
<script lang="javascript">

</script>