<div class="container">
    <div class="row">
        <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="bs-example" data-example-id="carousel-with-captions">
                        <div id="carousel-example-captions" class="carousel slide" data-ride="carousel">
                            <ol class="carousel-indicators">
                                <li data-target="#carousel-example-captions" data-slide-to="0" class="active"></li>
                                <li data-target="#carousel-example-captions" data-slide-to="1"></li>
                                <li data-target="#carousel-example-captions" data-slide-to="2"></li>
                                <li data-target="#carousel-example-captions" data-slide-to="3"></li>
                                <li data-target="#carousel-example-captions" data-slide-to="4"></li>
                            </ol>
                            <div class="carousel-inner" role="listbox">
                                <div class="item active">
                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>imagen1.png" alt="Unidad 1">
                                    <div class="carousel-caption">
                                    </div>
                                </div>
                                <div class="item">
                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>imagen2.png" alt="Unidad 2">
                                    <div class="carousel-caption">
                                    </div>
                                </div>
                                <div class="item">
                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>imagen3.png" alt="Unidad 3">
                                    <div class="carousel-caption">
                                    </div>
                                </div>
                                <div class="item">
                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>imagen4.png" alt="Unidad 4">
                                    <div class="carousel-caption">
                                    </div>
                                </div>
                                <div class="item">
                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>imagen5.png" alt="Unidad 5">
                                    <div class="carousel-caption">
                                    </div>
                                </div>
                                 <div class="item">
                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>imagen6.png" alt="Unidad 5">
                                    <div class="carousel-caption">
                                    </div>
                                </div>
                            </div>
                            <a class="left carousel-control" href="#carousel-example-captions" role="button" data-slide="prev">
                                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                                <span class="sr-only">Previous</span>
                            </a>
                            <a class="right carousel-control" href="#carousel-example-captions" role="button" data-slide="next">
                                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                                <span class="sr-only">Next</span>
                            </a>
                        </div>
                    </div><!-- /example -->
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-heading">Bandeja de Entrada</div>
                <div class="panel-body">
                     <div class="panel-body">
                         <br>
                   informacion de eventos 
                   </br>
                   Desgustaciones 
                   
                
                    <p><img src="http://www.blogodisea.com/wp-content/uploads/2010/04/pollito-bailon-chicken.gif" alt="pollito-bailon-chicken" /></p>
                    
                </div>
                  <div class="panel-body">
                    Aprovechen a finales del este mes de fabrero tendremos descuentos con del 50%
                    para poder consumir mas de nuestras bebidas hechas po nuestros aprendices 
                 </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-body">
                    Este aplicativon te ayudara a facilitar los  pedidos que realice en el punto de cafè la Angostura  
                    Haciendo pedidos por medio de una tablet y poder llevar la informaciòn de tu consumo en su correspondientes 
                    correos para estar màs informado de sus salidad de ingresos 
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    Nosotros lo invitamos a usted y a su familia en poder utilizar por primera vez nuestro software 
                    y poder interactuar con nuestra aplicaciòn fue creado para poder hacer la vida mas facìl
                    llevar la informaciòn de los registros de los pedidos 
                    En una forma màs ordenada para la hora de poder consultar  
                </div>
            </div>
            <div class="col-md-3"></div>
        </div>
    </div>


</div>
