<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">
        <link rel="icon" href="<?php echo $_layoutParams['ruta_img']; ?>favicon.ico">
        <title><?php echo $this->titulo; ?></title>
        <link href="<?php echo $_layoutParams['ruta_css']; ?>estilos.css" rel="stylesheet">
        <script src="<?php echo $_layoutParams['ruta_jquery']; ?>jquery-2.1.1.js"></script>
        <link href="<?php echo $_layoutParams['ruta_bootstrap']; ?>css/bootstrap.min.css" rel="stylesheet">
        <link href="<?php echo $_layoutParams['ruta_bootstrap']; ?>css/bootstrap-datetimepicker.min.css" rel="stylesheet">
        <script src="<?php echo $_layoutParams['ruta_bootstrap']; ?>js/bootstrap.min.js"></script>
        <script src="<?php echo $_layoutParams['ruta_bootstrap']; ?>js/moment.js"></script> 
        <script src="<?php echo $_layoutParams['ruta_bootstrap']; ?>js/bootstrap-datetimepicker.js"></script>        
        <script type="text/javascript" src="<?php echo $_layoutParams['ruta_js']; ?>jquery.simplyscroll.js"></script>
        <link rel="stylesheet" href="<?php echo $_layoutParams['ruta_css']; ?>jquery.simplyscroll.css" media="all" type="text/css">        
        <script type="text/javascript" src="<?php echo $_layoutParams['ruta_js']; ?>flipclock.js"></script>
        <script type="text/javascript" src="<?php echo $_layoutParams['ruta_js']; ?>nt.js"></script>
        <link rel="stylesheet" href="<?php echo $_layoutParams['ruta_css']; ?>flipclock.css" media="all" type="text/css"> 
    </head>
    <body>

