<div class="container">
    <div class="row">
        <div class="col-md-6">
            <div class="panel panel-default sombra">
                <div class="panel-body">
                    <div class="bs-example" data-example-id="carousel-with-captions">
                        <div id="carousel-example-captions" class="carousel slide" data-ride="carousel">
                            <ol class="carousel-indicators">
                                <li data-target="#carousel-example-captions" data-slide-to="0" class="active"></li>
                                <li data-target="#carousel-example-captions" data-slide-to="1"></li>
                                <li data-target="#carousel-example-captions" data-slide-to="2"></li>
                                <li data-target="#carousel-example-captions" data-slide-to="3"></li>
                                <li data-target="#carousel-example-captions" data-slide-to="4"></li>
                                <li data-target="#carousel-example-captions" data-slide-to="5"></li>
                                <li data-target="#carousel-example-captions" data-slide-to="6"></li>
                                <li data-target="#carousel-example-captions" data-slide-to="7"></li>
                                <li data-target="#carousel-example-captions" data-slide-to="8"></li>
                                <li data-target="#carousel-example-captions" data-slide-to="9"></li>
                            </ol>
                            <div class="carousel-inner" role="listbox">
                                <div class="item active">
                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>ovs1.jpg" alt="Unidad 1">
                                    <div class="carousel-caption">
                                    </div>
                                </div>
                                <div class="item">
                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>ovs2.jpg" alt="Unidad 2">
                                    <div class="carousel-caption">
                                    </div>
                                </div>
                                <div class="item">
                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>ovs3.jpg" alt="Unidad 3">
                                    <div class="carousel-caption">
                                    </div>
                                </div>
                                <div class="item">
                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>ovs4.jpg" alt="Unidad 4">
                                    <div class="carousel-caption">
                                    </div>
                                </div>
                                <div class="item">
                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>ovs5.jpg" alt="Unidad 5">
                                    <div class="carousel-caption">
                                    </div>
                                </div>
                                <div class="item">
                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>ovs6.jpg" alt="Unidad 6">
                                    <div class="carousel-caption">
                                    </div>
                                </div>                                
                                <div class="item">
                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>ovs7.jpg" alt="Unidad 7">
                                    <div class="carousel-caption">
                                    </div>
                                </div>
                                <div class="item">
                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>ovs8.jpg" alt="Unidad 7">
                                    <div class="carousel-caption">
                                    </div>
                                </div>
                                <div class="item">
                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>ovs9.jpg" alt="Unidad 7">
                                    <div class="carousel-caption">
                                    </div>
                                </div>
                                <div class="item">
                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>ovs10.jpg" alt="Unidad 7">
                                    <div class="carousel-caption">
                                    </div>
                                </div>
                            </div>
                            <a class="left carousel-control" href="#carousel-example-captions" role="button" data-slide="prev">
                                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                                <span class="sr-only">Previous</span>
                            </a>
                            <a class="right carousel-control" href="#carousel-example-captions" role="button" data-slide="next">
                                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                                <span class="sr-only">Next</span>
                            </a>
                        </div>
                    </div><!-- /example -->
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="panel panel-default sombra">
                <div class="panel-heading">Bandeja de Entrada</div>
                <div class="panel-body">
                   Fecha de partos
                   <br>
                   <br>
                   Vacas que estan en celo
                   <br>
                   <br>
                   Produccion de leche
                   <br>
                   <br>
                   Inseminación
                   <br>
                   <br>
                   Ventas
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default sombra">
                <div class="panel-body">
                    El Sistema de caracterización ganadera Oviboprino Soft muestra de una manera sistematizada y ordenada los registros y formularios del área ganadera del centro  de formación, permitiendo ver de una forma recopilada, didáctica y dispuesta; registrando toda actividad que se le realiza al ganado a diario especificando los registros individuales por medio del código que identifica al animal o el registro grupal. Este proyecto se hace con la necesidad de llevar a cabo los registros de cada labor o tarea que se realiza para así obtener resultados fijos en la producción, inventario, ingresos, entre otras; promoviendo el progreso del centro de formación en esta área o de la finca.
            </div>
        </div>
    </div>
</div>
