<div class="container">
    <div class="contenedor">


        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
            <!-- Indicators -->
            <ol class="carousel-indicators">
                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                <li data-target="#carousel-example-generic" data-slide-to="3"></li>
            </ol>

            <!-- Wrapper for slides -->
            <div class="carousel-inner">
                <div class="item active">
                    <img src="<?php echo $_layoutParams['ruta_img']; ?>img1.jpg" alt="...">
                    <div class="carousel-caption">

                    </div>
                </div>
                <div class="item">
                    <img src="<?php echo $_layoutParams['ruta_img']; ?>img2.jpg" alt="...">
                    <div class="carousel-caption">
                    </div>
                </div>
                <div class="item">
                    <img src="<?php echo $_layoutParams['ruta_img']; ?>img3.jpg" alt="...">
                    <div class="carousel-caption">
                    </div>
                </div>
                <div class="item">
                    <img src="<?php echo $_layoutParams['ruta_img']; ?>img4.jpg" alt="...">
                    <div class="carousel-caption">
                    </div>
                </div>
                <div class="item">
                    <img src="<?php echo $_layoutParams['ruta_img']; ?>img5.jpg" alt="...">
                    <div class="carousel-caption">
                    </div>
                </div> 
                <div class="item">
                    <img src="<?php echo $_layoutParams['ruta_img']; ?>img6.jpg" alt="...">
                    <div class="carousel-caption">
                    </div>
                </div>             </div>
        </div>

        <!-- Controls -->
        <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left"></span>
        </a>
        <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right"></span>
        </a>
    </div>
    <br>
    <div class="row">
        <div class="col-sm-6">
            <div class="panel panel-custom">
                <div class="panel-heading">
                    <h3 class="panel-title">Que es?</h3>
                </div>
                <div class="panel-body">
                    
 
Exporurales, la máxima expresión de feria en el programa Jóvenes Rurales Emprendedores del Sena, que muestra los resultados de las formaciones de los aprendices del sector rural de todo el país, contará dentro de su desarrollo con cinco componentes, como lo son los concursos de catación y barismo, muestra comercial, rueda de negocios, micro-rueda de empleo y una agenda académica con conferencistas internacionales
 
Se esperan aproximadamente 850 personas del Sena provenientes de las 33 regionales de Colombia y alrededor de 2500 como visitantes
                </div>
            </div>
        </div><!-- /.col-sm-4 -->
        <div class="col-sm-6">
            <div class="panel panel-custom">
                <div class="panel-heading">
                    <h3 class="panel-title">Rueda de negocios</h3>
                </div>
                <div class="panel-body">
                 
                           La Rueda de Negocios Expo Rurales  Emprendedores, “Desarrollando País a través del emprendimiento y empleo rural” en su versión 2014, es un evento en el que se encontrarán 20 compradores y 76 vendedores nacionales. Se pretenden lograr a lo largo de 352 citas posibles agendables: ampliación de la red ventas de las empresas participantes, transacciones exitosas, alianzas estratégicas y nuevas oportunidades de negocios en las 21 categorías que representan las unidades productivas y/o empresarios rurales, pertenecientes al programa Jóvenes Rurales Emprendedores del SENA.
                </div>
            </div>
        </div><!-- /.col-sm-4 -->
    </div>
</div>
</div>