<div class="container">
    <div class="row">
        <div class="col-md-1"></div>
        <div class="col-md-10">
            <div class="panel panel-warning sombra">
                <div class="panel-heading"><h4 class="label-orange">Registro Hoja de Vida Animal</h4></div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-12">
                            
                        </div>
                    </div>
                    <br />
                    <div class="row">
                        <div class="col-md-12  ">
                            <div class="table-responsive">
                                <table id="datatable" class="table table-condensed table-striped table-bordered table-hover">
                                    <thead>
                                        <tr class="warning">
                                            <th>Codigo</th>
                                            <th>Nombre Del Animal</th>
                                            <th>Nombre / Codigo Padre</th>
                                            <th>Nombre / Codigo Madre</th>
                                            <th>Peso</th>
                                            <th class="">Acciones</th>
                                        </tr>        
                                    </thead>
                                    <tbody>
                                        
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                    <a class="btn  btn-sm btn-success" href="<?php echo BASE_URL . 'oviboprinosoft/parametros/viewregistroanimal'; ?>" >Agregar</a>
                </div></div>
        </div>
        
        <div class="col-md-1"></div>
    </div>
</div>