<div class="container">
    <div class="row">
        <div class="col-md-6">
            <div class="panel panel-default sombra">
                <div class="panel-body">
                    <div class="bs-example" data-example-id="carousel-with-captions">
                        <div id="carousel-example-captions" class="carousel slide" data-ride="carousel">
                            <ol class="carousel-indicators">
                                <li data-target="#carousel-example-captions" data-slide-to="0" class="active"></li>
                                <li data-target="#carousel-example-captions" data-slide-to="1"></li>
                                <li data-target="#carousel-example-captions" data-slide-to="2"></li>
                                <li data-target="#carousel-example-captions" data-slide-to="3"></li>
                                <li data-target="#carousel-example-captions" data-slide-to="4"></li>
                            </ol>
                            <div class="carousel-inner" role="listbox">
                                <div class="item active">
                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>up1.jpg" alt="Unidad 1">
                                    <div class="carousel-caption">
                                        <h3>Unidad 1</h3>
                                        <p>Nota 1</p>
                                    </div>
                                </div>
                                <div class="item">
                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>up2.jpg" alt="Unidad 2">
                                    <div class="carousel-caption">
                                        <h3>Unidad 2</h3>
                                        <p>Nota 2</p>
                                    </div>
                                </div>
                                <div class="item">
                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>up3.jpg" alt="Unidad 3">
                                    <div class="carousel-caption">
                                        <h3>Unidad 3</h3>
                                        <p>Nota 3</p>
                                    </div>
                                </div>
                                <div class="item">
                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>up4.jpg" alt="Unidad 4">
                                    <div class="carousel-caption">
                                        <h3>Unidad 4</h3>
                                        <p>Nota 4</p>
                                    </div>
                                </div>
                                <div class="item">
                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>up5.jpg" alt="Unidad 5">
                                    <div class="carousel-caption">
                                        <h3>Unidad 5</h3>
                                        <p>Nota 5</p>
                                    </div>
                                </div>
                            </div>
                            <a class="left carousel-control" href="#carousel-example-captions" role="button" data-slide="prev">
                                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                                <span class="sr-only">Previous</span>
                            </a>
                            <a class="right carousel-control" href="#carousel-example-captions" role="button" data-slide="next">
                                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                                <span class="sr-only">Next</span>
                            </a>
                        </div>
                    </div><!-- /example -->
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="panel panel-default sombra">
                <div class="panel-heading">Bandeja de Entrada</div>
                <div class="panel-body">
                    Contenido de la bandeja de entrada
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default sombra">
                <div class="panel-body">
                    Esta aplicacion bla bla bla
                </div>
            </div>
        </div>
    </div>
</div>
